packages:
  # all packages in subdirs of packages/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

# Allow build scripts for these packages (pnpm 10+ security feature)
onlyBuiltDependencies:
  - better-sqlite3

ignoredBuiltDependencies: []

minimumReleaseAge: 4320
# trustPolicy: "no-downgrade"
blockExoticSubdeps: true

trustPolicyExclude:
  - 'tinyexec@1.2.2'

strictDepBuilds: true
minimumReleaseAgeExclude:
  - '@gingacodemonkey/config'
trustPolicyIgnoreAfter: 43200
trustPolicy: no-downgrade
