packages:
  # all packages in subdirs of packages/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

# Allow build scripts for these packages (pnpm 10+ security feature)
onlyBuiltDependencies:
  - better-sqlite3

ignoredBuiltDependencies: []