name: ESLint Auto-fix and Check

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:

      # 0. Stop infinite loop
      - name: Check if commit is made by bot
        if: github.actor == 'github-actions[bot]'
        run: echo "Commit made by bot. Exiting workflow." && exit 0

      # 1. Checkout the repository with credentials persisted for push
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.head_ref || github.ref_name }}

      # 2. Set up pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # 2.1. Cache pnpm store
      - name: Get pnpm store
        id: pnpm-cache-store
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # 2.2. Cache pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 4. Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
